### ISSUE TITLE
RNN: indices

### ISSUE THREAD

**Issue by KerstinKaspar** [kashefy/mi1notes#39]
There are a few indices mixed up on the slides of RNN (Tut. 7), I think. p. 19 (first line) gi > go and p.21 forget gate weights o > f. There also don't seem to be the notes on ISIS and I cannot get them from the repository either, but I don't know whether that's intentionally. Thank you for the great studying material!

**Comment by kashefy** [comment]
Thanks @KerstinHut , I've fixed superscripts.
The "notes" version for the RNN gets generated but it doesn't have anything that is not also in the slides. But the layout is completely off so I excluded them from ISIS. You can always grap the generated pdfs from the [releases](https://github.com/kashefy/mi1notes/releases).
